### ISSUE TITLE
Incompatible with terraforged 1.18.2's alpha release

### ISSUE THREAD

**Issue by Shadowex3** [Apothicon02/Ecospherical-Expansion#1]
It will load and generate worlds, however terraforged alpha's unique behavior with producing forests and trees will interact with this mod and create a massively overloaded forest with way too many vines and particles. Under ordinary circumstances I get 100+fps with 32 chunk render distances even while floating above a forest. In this case I was in the _single digits_ while this was being rendered.

**Comment by Apothicon02** [comment]
this is the fault of terraforged and it happens with every biome mod. They need to fix it.
