### ISSUE TITLE
[Suggestion] A world preset that includes "continents" of each world preset

### ISSUE THREAD

**Issue by MrKashew** [Apothicon02/Ecospherical-Expansion#2]
Not sure how realistic this is to implement - but all the world types are intriguing - it would be especially interesting to explore a world full of all the types, transitions would have to be thought out or left as drastic however, what are your thoughts on this

Likely more sensible for regions that have less drastic changes between them

**Comment by Apothicon02** [comment]
There wouldn't be any easy enough way to make the transitions between continents of different presets look any good.
