### ISSUE TITLE
Console error spaming

### ISSUE THREAD

**Issue by JuanPacoPedrodelaMar** [Apothicon02/Ecospherical-Expansion#3]
There is an error that it is continously spamming in console which is this:
[Worker-Main-14/ERROR]: Detected setBlock in a far chunk [302, -380], pos: class_2338{x=4832, y=67, z=-6078}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / eco:bushes_super_dense]
I´m using Fabric 2.2.0 version of the mod in minecraft 1.20.1 on a multiplayer server.

**Comment by Apothicon02** [comment]
This mod isnt being updated anymore but the successor doesnt have this issue.
