### ISSUE TITLE
Grass generating on top of trees

### ISSUE THREAD

**Issue by LunarDev-git** [Apothicon02/Ecospherical-Expansion#4]
## Client Information

Modloader; Forge
Forge Version: 47.2.19
Minecraft Version:  1.20.1

## Bug Description

When I start a new world (-209305406949967401) and I generate it with Eco, trees become... hairy is the best way to put it. I can't see anything about this being intentional? This happens on all trees. Looks really out of place, especially in the cherry biome

Without Mod: 
![image](https://github.com/Apothicon02/Ecospherical-Expansion/assets/105180230/1677711a-37ec-4779-97ef-6e57f038260f)

With Mod: 
![image](https://github.com/Apothicon02/Ecospherical-Expansion/assets/105180230/6dd1bc12-b11b-4cab-8c97-707946dbf0af)

**Comment by Apothicon02** [comment]
this mod isnt being updated anymore but the successor will not have this issue
