### ISSUE TITLE
[Suggestion] Waterworld variants of other presets other than Tropospherical

### ISSUE THREAD

**Issue by dandalous** [Apothicon02/Ecospherical-Expansion#5]
Is there a way to make presets other than Tropospherical have an endless ocean? I like the endless ocean because it helps prevent floating structures like this (though I still get villages on the ocean but I can compromise with that). I could just disable structures but some of them are necessary for progression (like the End Fortress) and villages are QoL. Alternatively I could use something like Ex Nihilo but I'm not a fan of that kind of progression. I figured out how to change Tropospherical's Nether to be Vanilla (for Amplified Nether) by editing some json file, so I'm assuming an endless ocean can be achieved similarly?
![2024-01-04_09 42 42](https://github.com/Apothicon02/Ecospherical-Expansion/assets/125793933/a22651c1-8938-4db9-9591-ae353b16537b)

I'd want to play on other presets like Mesospherical and Stratospherical because you can get some jaw-dropping scenery.
![2024-01-04_07 03 26](https://github.com/Apothicon02/Ecospherical-Expansion/assets/125793933/72323c92-ad06-4fec-9c6d-aeba856b75b7)
![2024-01-04_07 00 32](https://github.com/Apothicon02/Ecospherical-Expansion/assets/125793933/2e18812c-480e-438e-8823-7d90918f74fc)
![2024-01-04_07 03 45](https://github.com/Apothicon02/Ecospherical-Expansion/assets/125793933/ca923df5-9283-4f25-abf2-698d6ef798c4)

**Comment by Apothicon02** [comment]
this mod isnt being updated anymore but the successor will have this feature.
