### ISSUE TITLE
Falling sand and tons of lag

### ISSUE THREAD

**Issue by Wakatsu** [Apothicon02/Ecospherical-Expansion#6]
A problem affecting ALL "floating island" types. If an island has sand or gravel in its composition, those will fall upon loading, creating a TON of lag, easily capable of downing a server. Not to mention that even if your server survives this, the mess left behind is all but pretty.

Maybe swap sand in generation for any non-gravity-affected block? Or make sure the underbelly of the islands is made of such blocks at least? I'm tired of starting a new world every time I find a Jungle or Mesa.

**Comment by Apothicon02** [comment]
Issue is not present with just eco or eco + bio. Has to be the fault of another mod you have or a very rare un-reproducable case.

**Comment by xxrancidbinxx** [comment]
![image](https://github.com/user-attachments/assets/7ba7d4b8-5629-4270-80f0-f13ca1799100)

Found this desert on the Tropospherical generation type, with only eco 2.4.6 + bio 2.1.1 (and JEI + addons, but that shouldn't matter) and destroyed my pretty good pc for 5 minutes while all the sand and cacti was falling. Also found another one at (2050, 18600) (same seed) so this isn't a rarity. Definitely an issue that needs reopening
