### ISSUE TITLE
(Lithospherical preset) Almost all Ancient Cities spawn either underground or underwater

### ISSUE THREAD

**Issue by DARKLOL680** [Apothicon02/Ecospherical-Expansion#7]
![2024-03-24_20 50 52](https://github.com/Apothicon02/Ecospherical-Expansion/assets/121734819/e1de278c-e9dd-49b6-8318-512ae2ca5ad8)
![2024-03-24_20 48 56](https://github.com/Apothicon02/Ecospherical-Expansion/assets/121734819/fa115bb5-86ae-4fe8-9e13-6d8b663760ef)
with the Lithospherical preset almost all Ancient Cities spawn buried underground or underwater

**Comment by Apothicon02** [comment]
cant do anything about it

**Comment by DARKLOL680** [comment]
:(
that's unfortunate, but thanks for replying
