### ISSUE TITLE
Tropospherical should spawn you on land

### ISSUE THREAD

**Issue by xxrancidbinxx** [Apothicon02/Ecospherical-Expansion#8]
Making a modpack using this world gen type and I find myself spawning in the water all the time which is fine in creative mode, but when you're in survival and the whole point of the world gen is having nothing to swim to? It becomes unplayable. I also tested this with just eco 2.4.6 + bio 2.1.1 and the same happens.

**Comment by Apothicon02** [comment]
Theres 3 solutions: 
- Keep regenerating the world until you spawn on land
- Go into creative or spectator for a moment to get up to land (for servers you can just do this and set the world spawn on land)
- Loot the oceans until you get enough blocks to get up to land. 

Guaranteeing you spawn on land would significantly slow world creation speed down.
